name: lon-sw-01
device_role:
  name: lleaf
id: a57c6cae-c896-4838-ba5e-3255325014f4
local_context_data:
  bgp_asn: 65000
  bgp_intfs:
    - swp1
device_type:
  manufacturer:
    name: NVIDIA1
interfaces:
  - name: loopback0
    ip_addresses:
      - address: 198.51.100.1/32
